osrf/lrauv

lrauv_ignition_plugins/worlds/empty_environment.sdf
* Use same step size
* Remove contact
* Update GUI plugins (which we should eventually move to a GUI config)
=> Update empty_environment to match buoyant_tethys

lrauv_ignition_plugins/src/ScienceSensorsSystem.cc
@mabelzhang , here's the approach I mentioned that we can use to detect when the spherical coordinates are set.
If you run `buoyant_tethys.sdf`, you'll see the warning message at startup. If you run `empty_environment.sdf`, you'll see it when the first vehicle is spawned.
Let me know what you think!
=> Science sensors: detect when spherical coordinates are set

lrauv_ignition_plugins/src/TethysCommPlugin.cc
This micro-PR adds water velocity as one of the parameters we care about.
=> Add water velocity.

lrauv_ignition_plugins/test/test_spawn.cc
The test started failing, it looks like we're sinking more than usual.
=> Increase depth tolerance for spawn test

docker/empty_world/Dockerfile
Precisely what the title says. A very minor issue with newline escaping in our Dockerfile.
=> Minor fixes to empty_world/Dockerfile

docker/debug_integration/Dockerfile, docker/tests/Dockerfile
=> Use latest Docker image instead of garden

lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/src/TethysCommPlugin.hh, lrauv_ignition_plugins/worlds/buoyant_tethys.sdf, lrauv_ignition_plugins/worlds/buoyant_tethys_at_depth.sdf, lrauv_ignition_plugins/worlds/empty_environment.sdf
We recently added a GUI plugin that displays points on a map, and I think it's helpful to use it here. Happy to see that the science data seems to be in place - Tethys is located at the small line on the bottom of the 3D scene.
=> Add NavSat GUI plugin

lrauv_system_tests/CMakeLists.txt, lrauv_system_tests/test/CMakeLists.txt, lrauv_system_tests/test/simulation/CMakeLists.txt, lrauv_system_tests/test/simulation/test_spawn.cc, lrauv_system_tests/test/simulation/test_state.cc, lrauv_system_tests/worlds/buoyant_tethys.sdf, lrauv_system_tests/worlds/empty_environment.sdf
Depends on https://github.com/osrf/lrauv/pull/195. For review, focus on https://github.com/osrf/lrauv/commit/572a9de25bbbc686cc09898af410894882ad8385 until rebase.
=> Add simulation tests to `lrauv_system_tests` package.

lrauv_system_tests/test/CMakeLists.txt, lrauv_system_tests/test/missions/CMakeLists.txt, lrauv_system_tests/test/missions/test_depth_vbs_mission.cc, lrauv_system_tests/test/missions/test_pitch_and_depth_mass_vbs_mission.cc, lrauv_system_tests/test/missions/test_pitch_mass_mission.cc, lrauv_system_tests/test/missions/test_yoyo_circle_mission.cc
Depends on #195. For review, focus on https://github.com/osrf/lrauv/commit/f573b14d14751971de77dde25ac3d7750e546977 until rebase.
=> Add mission tests to `lrauv_system_tests` package.

lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/src/SpawnPanelPlugin.cc, lrauv_ignition_plugins/src/SpawnPanelPlugin.hh, lrauv_ignition_plugins/src/SpawnPanelPlugin.qml, lrauv_ignition_plugins/src/SpawnPanelPlugin.qrc, lrauv_ignition_plugins/worlds/empty_environment.sdf, lrauv_ignition_plugins/worlds/portuguese_ledge.sdf.em
This PR adds a plugin which spawns a copy of the tethys vehicle at a given location.
=> Adds a plugin which spawns tethys

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/proto/CMakeLists.txt, lrauv_ignition_plugins/src/AcousticCommsPlugin.cc, lrauv_ignition_plugins/src/ControlPanelPlugin.cc, lrauv_ignition_plugins/src/HydrodynamicsPlugin.cc, lrauv_ignition_plugins/src/RangeBearingPlugin.cc, lrauv_ignition_plugins/src/ReferenceAxis.cc, lrauv_ignition_plugins/src/ScienceSensorsSystem.cc, lrauv_ignition_plugins/src/SpawnPanelPlugin.cc, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/src/TimeAnalysisPlugin.cc, lrauv_ignition_plugins/src/WorldCommPlugin.cc, lrauv_ignition_plugins/src/WorldConfigPlugin.cc, lrauv_ignition_plugins/src/comms/CMakeLists.txt, lrauv_ignition_plugins/src/comms/models/CMakeLists.txt, lrauv_ignition_plugins/src/comms/models/SimpleAcousticModel.cc, lrauv_ignition_plugins/worlds/empty_environment_with_tiles.sdf.em, lrauv_system_tests/CMakeLists.txt, lrauv_system_tests/test/dynamics/test_hydrodynamics.cc, lrauv_system_tests/test/missions/test_depth_vbs_mission.cc, lrauv_system_tests/test/missions/test_pitch_mass_mission.cc, lrauv_system_tests/test/missions/test_yoyo_circle_mission.cc, lrauv_system_tests/test/simulation/test_spawn.cc, lrauv_system_tests/test/simulation/test_state.cc, lrauv_system_tests/test/vehicle/test_ahrs.cc, lrauv_system_tests/test/vehicle/test_propeller_action.cc, lrauv_system_tests/test/vehicle/test_sensor.cc, lrauv_system_tests/test/vehicle/test_sensor_timeinterpolation.cc
Brings changes from `main` into the dvl branch and addresses `lrauv_ignition_plugins/CMakeLists.txt` conflicts. Also pulls in  `empty_environment_with_tiles.sdf.em` with the `DopplerVelocityLogSystem` added.
=> merge main to dvl branch and resolve confilicts

docker/debug_integration/Dockerfile, docker/tests/Dockerfile, lrauv_system_tests/test/environment/test_surface_winds.cc, lrauv_system_tests/worlds/buoyant_tethys.sdf, lrauv_system_tests/worlds/buoyant_tethys_at_depth.sdf
Precisely what the title says.
=> Fix local CI

.github/workflows/ci.yaml
=> Fix Gazebo Garden rebuild checks in PRs

docker/tests/Dockerfile
Pretty much the title says. Nth follow-up PR after #239.
=> Ensure CI reports test failures

lrauv_system_tests/test/vehicle/test_ahrs.cc
This should fix the flaky failures in AHRS tests.
=> Increase tolerance in AHRS tests

lrauv_gazebo_plugins/CMakeLists.txt
=> Fix Gazebo python bindings check

.github/workflows/ci.yaml
Follow-up after #256. Stage name changed and it was not reflected.
=> Use proper docker stage for CI

tools/setup/workspace.sh
A small quality of life improvement for devs.
=> Allow preexisting workspaces setup

tools/setup/workspace.sh
Connected to #266. Fixes unbound variable errors.
=> Relax workspace script errors

lrauv_system_tests/test/vehicle/test_acoustic_comms_multi_vehicle.cc
This PR fixes the flaky multi vehicle acoustic comms test.
=> Fix flaky acoustic comms tests

lrauv_description/hooks/hook.dsv.in, lrauv_description/hooks/hook.sh.in, lrauv_gazebo_plugins/hooks/hook.dsv.in, lrauv_gazebo_plugins/hooks/hook.sh.in
We are still using the old IGN environment variables. This PR migrates them to gz.
=> Migrates the hook files

tools/setup/gz-garden.yaml
Precisely what the title says.
=> Use Gazebo Garden branches

README.md
Add our paper citation so people can cross-reference easier.
DOI isn't out yet :woman_shrugging: Probably won't be for months.
=> Add paper citation to README
