docker/debug_integration.sh
This PR adds a `set -e` command to make sure the script exits if the source fails to build for some reason. The previous behaviour was annoying as it would execute the last good image, this leads to a lot of confusion when debugging.
=> [QOL improvement] Exit if the docker image does not build

lrauv_ignition_plugins/test/test_spawn.cc
I noticed the spawn test failing on CI. This should make it more robust to transport timing.
=> Increase tolerance of depth and pitch on spawn test

lrauv_ignition_plugins/test/test_spawn.cc
I was too ambitious on #61, the current tight tolerance is flaky, see [failure](https://github.com/osrf/lrauv/runs/4113119416?check_suite_focus=true)
```
2021-11-05T03:25:43.8355456Z 9: /home/developer/lrauv_ws/src/lrauv/lrauv_ignition_plugins/test/test_spawn.cc:161: Failure
2021-11-05T03:25:43.8356431Z 9: The difference between 0.0 and poses1.back().Pos().X() is 2.1789064913657771e-06, which exceeds tightTol, where
2021-11-05T03:25:43.8356995Z 9: 0.0 evaluates to 0,
2021-11-05T03:25:43.8357586Z 9: poses1.back().Pos().X() evaluates to -2.1789064913657771e-06, and
2021-11-05T03:25:43.8358198Z 9: tightTol evaluates to 9.9999999999999995e-07.
```
=> Relax spawn tight tolerance

lrauv_description/models/tethys/model.sdf, lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/example/example_buoyancy.cc, lrauv_ignition_plugins/proto/lrauv_command.proto, lrauv_ignition_plugins/proto/lrauv_state.proto, lrauv_ignition_plugins/src/TethysCommPlugin.cc
Part of #48 
* Document `buoyancyAction` and `buoyancyPosition`. Looking at the code history, it looks like at some point cc (cubic centimeter) was used as a unit, but AFAICT, both our plugins and the controller are consistently using cubic meters, so I documented this.
* Made the `LRAUV_example_buoyancy` more flexible so we can test different volumes.
* Checked that `test_buoyancy_action` has correct expectations
* Updated the TODO in the `buoyancy_engine` link, becuase I believe we have a different issue now. 
It would be good to have some eyes on this PR by people who have been involved in the original implementation (@mabelzhang / @arjo129 ), just to make sure I didn't miss anything related to units and the inertial TODO.
=> Document buoyancy action / VBS

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/example/example_elevator.cc, lrauv_ignition_plugins/proto/lrauv_command.proto, lrauv_ignition_plugins/test/test_elevator.cc
Part of #48 
* Added example executable that controls just the elevator
* Fixed the forward direction in the lift-drag plugin to be -X, because the link's -X is facing the forward direction. But I think that what really matters is the axis, not necessarily the direction.
* Documented the direction of the elevator joint angle
* Added a test that checks that the vehicle goes down for a positive elevator angle when propelled forward.
---
I checked manually that the behaviour doesn't seem to be entirely correct though. I'd expect a positive angle of attack to generate lift on the back of the vehicle, so it tilts forward and goes down when propelled forwards. But at low thrust, the vehicle is going up. The higher the thrust, the more it arches downwards. In all cases though, the oscillation of …
=> Elevator example, test and docs

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/src/TethysCommPlugin.hh
Because I can't see other printouts amidst this spam (and it was my spam too).
=> Toggle TethysCommPlugin debug printout

lrauv_ignition_plugins/src/VisualizePointCloud.cc, lrauv_ignition_plugins/src/VisualizePointCloud.hh, lrauv_ignition_plugins/src/VisualizePointCloud.qml
In the interest of eventually upstreaming the visualization plugin to `ign-gazebo` (i.e. https://github.com/ignitionrobotics/ign-gazebo/issues/1156), I'm making some suggestions to keep the plugin generic. This also means it will automatically scale to other science data sensors that we add in the future.
* Instead of hardcoding all `FloatV` topics, populate the dropdown with all topics publishing that message type
* Take min / max value from the current float data (this may be inefficient, and potentially change the color for the same sample with each new message)
* Made the colors configurable from the GUI
These are just some initial improvements to make sure we're not locking the plugin into a single use case. There are many more usability and functionality fixes that we need to make …
=> Suggestions to #70

docker/debug_integration/Dockerfile, docker/tests/Dockerfile
No need for the pre-release repo anymore. This shouldn't really be changing anything at this point, but it's safer.
Once we go to Garden (#54 ), we should add the nightly repo.
=> Remove pre-release repos, Fortress is stable

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh, lrauv_ignition_plugins/test/test_controller.cc, lrauv_ignition_plugins/test/test_mission_yoyo_circle.cc, lrauv_ignition_plugins/test/test_state_msg.cc
From #76:
> The formula on TethysComm was using 0.0016 m for the propeller diameter, but the Thruster uses 0.2 m, taken from the SDF.
Well... I forgot the `^4` ... `0.0016 == 0.2 ^ 4` :grimacing: This PR reverts it back.
>  I updated TethysComm to use 0.2 m, and that made the vehicle extremely fast. So I reduced the coefficient 100x to compensate.
This PR reverts it back... :grimacing: 
> Updated a few test expectations to the new thrust.
Yeah, updating that again...
> we're converting from ang vel to force and back. It would reduce errors if we only converted once.
Case in point :upside_down_face: 
---
I discovered this while working on a test for the state message on #81 . I broke off just the `propOmega` checks into this PR.
=> 🤦‍♀️ Fix thruster coefficient

lrauv_ignition_plugins/src/TethysCommPlugin.cc
`TethysComm` has been publishing the latest state even while simulation is paused. 
Not publishing while paused helps with debugging, because if we're echoing messages or checking console logs, we can step through them and analyze the latest data slowly. This may also help the controller, I'm not sure what it's doing with all these repeated messages that it is receiving.
One downside of this is that some sensor data may be received between the last publish and the pause, and it won't be published until unpause. But I'm not sure this causes any actual issues.
---
I also went ahead and deleted an unused variable, and moved another one down closer to where it is used.
=> Don't publish LRAUV state while paused

lrauv_ignition_plugins/src/WorldCommPlugin.hh
`WorldCommPlugin.hh` includes an `lrauv_command.pb.h` but doesn't use it:
https://github.com/osrf/lrauv/blob/d6c305f331f87d5994086dc3087c020cd71ebaf7/lrauv_ignition_plugins/src/WorldCommPlugin.hh#L33
Furthermore, the CMake file does not declare any dependency on `lrauv_command.pb.h`:
https://github.com/osrf/lrauv/blob/d6c305f331f87d5994086dc3087c020cd71ebaf7/lrauv_ignition_plugins/CMakeLists.txt#L165
In rare scenarios this can lead to builds which fail. Since I cannot see any instances where `lrauv_command.pb.h` is used  by `WorldCommPlugin.hh` or `WorldCommPlugin.cc` I am removing it.
=> Remove unused include to solve potential build inconsistencies.

lrauv_ignition_plugins/test/test_mission_yoyo_circle.cc
For whatever reason our vehicle seems to be overdiving when performing YoYo. At this point it makes little sense to keep the expectations too tight as we still have some way to go before we understand the true nature of the overdiving.
=> Temporary fix for issue #92.

README.md, lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/src/ScienceSensorsSystem.cc, lrauv_ignition_plugins/src/VisualizePointCloud.cc
[Ignition Common's profiler](https://ignitionrobotics.org/api/common/4.4/profiler.html) is very handy to debug performance issues. I'm planning to use it to look into the performance of the markers.
This PR just sets up the profiler and adds some profiling points. These points will change with PRs like #70, so don't worry too much about them right now, they're just placeholders.
Example output:
=> Setup profiler

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/proto/lrauv_state.proto, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/src/TethysCommPlugin.hh
The density value is used by the vertical controller in the LRAUV's controller. Because we have not been populating this field with a non-zero value, the Vertical Controller would crash. For more robustness, the controller itself should start of with a default density value. 1000kgm^3 could be a good value.
=> Update density value in tethys comm plugin.

lrauv_ignition_plugins/src/ScienceSensorsSystem.cc, lrauv_ignition_plugins/src/VisualizePointCloud.cc, lrauv_ignition_plugins/src/VisualizePointCloud.hh, lrauv_ignition_plugins/worlds/buoyant_tethys.sdf
This addresses this comment by @mabelzhang : https://github.com/osrf/lrauv/pull/93#issuecomment-985776670
* Needs this to reduce warnings, but not for functionality: https://github.com/ignitionrobotics/ign-gui/pull/326
---
* Added services for all `FloatV`s, which were missing. This is needed to get the data on demand, since Ignition Transport doesn't support latching.
* Make the `FloatV` optional. This is not a use case here, but I think it's a nice-to-have when we upstream.
* Instead of skipping NaNs when displaying, send a `DELETE_MARKER` command, so that if the data changes from valid to `NaN` it disappears.
* Removed the `-` from the marker namespaces because it looked awkward when there's no float topic
=> Cleanup old science values and improve initial subscription

lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh
In many cases we find "flaky" mission integration tests. Often this is because of components crashing on the LRAUV controller side. This often leads us down a very painful debugging journey. This patch proposes the following change: if there is an error reported by the LRAUV application, report it. The hope is that this will save us valuable time when debugging.
=> Log LRAUV application errors as errors.

lrauv_ignition_plugins/test/test_mission_yoyo_circle.cc
Occassionally it may take time for the yoyo mission to get started. Hence, the system may have a velocity of zero for the first few iterations. This PR starts the velocity check after few iterations.
=> Allow for time taken for YoYo to start

lrauv_ignition_plugins/proto/lrauv_command.proto, lrauv_ignition_plugins/proto/lrauv_init.proto, lrauv_ignition_plugins/proto/lrauv_state.proto, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/src/TethysCommPlugin.hh, lrauv_ignition_plugins/src/comms/CommsPacket.cc
* Broken off of #81 
* Part of #48 
The largest part of the diff is just updating the documentation style to use doxygen, even if we're not actually generating docs for this project, that makes it easier to read and maintain.
Also made it explicit which fields are not used or populated. The idea is that we update those as we start using them.
The fields that I'm planning on updating with new reference frames have `TODO(chapulina)`.
=> Update message documentation style

lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh
* Follow up to https://github.com/osrf/lrauv/pull/114
* See comment https://github.com/osrf/lrauv/pull/114#discussion_r770811257
I left the errors there because there haven't been too many of them and they may provide useful context.
I also removed the `LRAUV Application reported error` because I think it was adding too much extra text to the logs.
=> Also report critical errors on tests

lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh
That has changed on the new Docker images.
A separate "issue" is that the missions now don't terminate on critical failures, so they're running until the timeout - which causes CI to take longer and test expectations to fail (we get more drift, etc).
=> Update quit string on tests

lrauv_ignition_plugins/src/ScienceSensorsSystem.cc
A quick review. Just guards all `igndbg` commands related to interpolation with a Boolean so it doesn't print so much stuff on CI.
I started commenting out the lines, but there are tens of them. Since I'm still actively debugging the interpolation, I added a Boolean flag. It'll probably be there until science missions check out, which means weeks or months.
=> Add debug printout flag for barycentric interpolation

lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh, lrauv_ignition_plugins/test/test_mission_depth_vbs.cc, lrauv_ignition_plugins/test/test_mission_pitch_and_depth_mass_vbs.cc, lrauv_ignition_plugins/test/test_mission_pitch_mass.cc, lrauv_ignition_plugins/test/test_mission_yoyo_circle.cc, lrauv_ignition_plugins/test/test_state_msg.cc
Thanks to @braanan , now the missions don't end up in critical errors anymore. Which means that they run until their timeouts, which are very large (hours).
Our tests had been relying on the missions ending relatively quickly until now, and with the latest fixes, they're running forever (I had to cancel GitHub actions that was running for 1.5 hours on #121).
Instead of updating the mission timeouts and relying on the LRAUV application terminating on its own, the idea on this PR is that the tests should know when they've received enough data and terminate the application then.
We've been killing the application anyway because of #4 , so now we're actually taking advantage of that.
=> Mission tests: kill LRAUV application after enough iterations

lrauv_ignition_plugins/worlds/buoyant_tethys.sdf
* Broken off #88 
Breaking this small change from the larger PR so it can be discussed if needed. The default grid is 20mx20m, which is a bit restrictive for our use case. This PR increases it to 100mx100m and leaves the `GridConfig` plugin available so users can quickly access it to change the grid. I find that useful when measuring distances.
=> Grid: modify default grid and add GUI plugin

lrauv_ignition_plugins/src/ScienceSensorsSystem.cc, lrauv_ignition_plugins/worlds/buoyant_tethys.sdf
* Broken off #88 
Tests were crashing for that PR, while investigating, I noticed it happened because the `MINIATURE_SCALE` had been removed.
This PR removes the miniature scale and prints a warning instead of segfaulting, but I haven't looked closely into the barycentric interpolation to see why the miniature scale caused the issue, could you take a look @mabelzhang ?
I also added other changes from #88 which help us not need the miniature scale:
* The invisible ground plane makes it possible to easily scroll to a far away distance
* This can be seen with the 300kmx300km grid that is also added here
* The increased camera clipping distances are also needed to see the entire grid from a distance
* Added the camera controls plugin so the user can easily go back to the initial camera angle
=> Remove miniature scale from science data and fix segfault

docker/tests/Dockerfile, lrauv_ignition_plugins/CMakeLists.txt
Quick update since we have new dependencies on Garden. Note that `ign-math`, `sdf` and `ign-physics` have also been bumped, so be sure to update your local workspaces.
=> Update Garden dependencies

lrauv_ignition_plugins/test/test_mission_pitch_mass.cc
These are the new test expectations written by @arjo129 in #96. I'd like to see how the tolerances progress as we go from the current `main`, to #89 and finally to #96.
It's good to decouple the test changes from the fixes so we can compare test results from before and after.
The only differences from the test here and the one on #96 are the tolerances for pitch, X and Z.
=> Port pitch mass test updates from #96

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/src/TethysCommPlugin.cc
Resolves #136. This PR updates the thruster coefficient used. The exact math for how it was calculated can be found here:
https://colab.research.google.com/drive/1L-qDb3AYA6JJChWPxn4BU0RppXX8x8t0?usp=sharing
=> Updated new thruster coefficient

lrauv_description/models/tethys_equipped/model.sdf, lrauv_description/test/worlds/flat_world.sdf, lrauv_description/test/worlds/tilted_world.sdf, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/worlds/acoustic_comms_test.sdf, lrauv_ignition_plugins/worlds/buoyant_tethys.sdf
* Targeted at #96 
I added a few more water density updates, and fixed a bug on `TethysCommPlugin` that was making it use the wrong water density.
=> Fix ocean density on TethysComm

docker/tests/Dockerfile
The upgrade will skip thing that require new packages. Such as new ignition libraries which are what we're looking for going to the nightlies.
This is a follow up to https://github.com/osrf/lrauv/pull/128#issuecomment-1006103394 https://github.com/osrf/lrauv/commit/e1ebc3a7e3b4f2e4664a781f05be823ebce46e6a
Reproducing the upgrade it skips a lot
<details>
```
root@6e59e94e5c93:/home/developer/lrauv_ws/src/lrauv-application# apt-get upgrade -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
ignition-garden libegl-mesa0 libegl-mesa0:i386 libgbm1 libgbm1:i386 libgl1-mesa-dri libgl1-mesa-dri:i386 libglapi-mesa
libglapi-mesa:i386 libglx-mesa0 libglx-mesa0:i386 …
```
=> use a dist-upgrade not just upgrade

lrauv_description/models/tethys/model.sdf.in, lrauv_description/scripts/description_generator.py
While working on #48, I went over the model generation code and refactored it a bit to make it easier for a new user to understand what it's doing. Some of the changes:
* Removed for loops over `sdf` and `model` tags, because there's only one of each
* Consistently used the `_tag` suffix for variables that hold XML tags
* Renamed `main_body` to `base_link` to be consistent with SDF
* Handle only one float value for X moments, instead of an array that always has 5 zeroes
* Added more assertions and comments throughout to make flow more explicit
* Refer to links by name instead of indirectly getting to them based on whether or not they have a property
* Don't pass the `total_mass` global variable as an argument
@arjo129 , these are just suggestions based on my understanding. Let me know if …
=> Refactor model generation for readability

lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh
Currently, the `LrauvTestFixture` allows us to only load `BuoyantTethys.sdf`. This PR refactors the test fixture. It creates two test classes:
* `LrauvTestFixtureBase` - An abstract base class which contains all the common functionality.
* `LrauvTestFixture` - Inherits from `LrauvTestFixtureBase` and loads the `buoyant_tethys.sdf`.
=> Refactor Test Fixture to support different worlds 

lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh, lrauv_ignition_plugins/test/test_mass_shifter.cc, lrauv_ignition_plugins/worlds/buoyant_tethys.sdf, lrauv_ignition_plugins/worlds/buoyant_tethys_at_depth.sdf
Depends on #160
This PR adds a surface at z=0 to the default `buoyant_tethy.sdf`.  Most things work as expected. I had to move the MassShifter test deeper underwater as the vehicle would not pitch enough at the surface (kind of expected I guess?). I moved the mass shifter test deeper underwater.
=> Add surface to buoyant_tethys

lrauv_ignition_plugins/proto/lrauv_state.proto, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/test/test_state_msg.cc
Wrapping up #48 :checkered_flag: :raised_hands: :smiling_face_with_tear: 
This PR populates `ratePQR` and `rateUVW`, which are the quantities expressed in the FSK frame.
Note that the model itself is oriented as "SFU" (starboard, forward, up). See discussion on #48 on why it was tough to orient the model as FSK and save the extra transform. One way to visualize the SFU frame is using the transform control tool:
**ENU** :point_down: .................................................................. **FSK** :point_down:  / **SFU** :sparkles: .....................................................................  **NED** :point_down:
=> State message: populate UVW and PQR rates

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/test/test_ahrs.cc, lrauv_ignition_plugins/worlds/buoyant_tethys.sdf
Combining upstream IMU and magnetometer sensors. This is lacking a test but perhaps this is best tested as part of #151 e.g. make the AUV describe a known trajectory and sample IMU and magnetometer measurements along that trajectory to ensure values make sense.
=> Add AHRS to Tethys equipped model

lrauv_ignition_plugins/proto/lrauv_init.proto, lrauv_ignition_plugins/src/WorldCommPlugin.cc, lrauv_ignition_plugins/src/WorldCommPlugin.hh, lrauv_ignition_plugins/test/test_spawn.cc
This PR adds an acomms modem address entry to `lrauv_init` message and modifies the SDF string formulation in `WorldCommPlugin` to propagate the specified address to a spawned vehicle. 
This PR depends on [#376](https://bitbucket.org/mbari/lrauv-application/pull-requests/376/byraanan-ign-init-acomms-address) in lrauv-application.
The acomms modem address is specified by the `Vehicle.id` configuration parameter in LRAUV application. That config can be found under `Config/vehicle.cfg`.
@chapulina, Louise, I added calls to set the acomms address for spawned vehicles in [lrauv_ignition_plugins/test/test_spawn.cc](https://github.com/osrf/lrauv/compare/braanan/init_acomms_address?expand=1#diff-da5f11524c6c0f34dbe1bd06604a8755c0f01bdedbb3da7d95b8922daaa01c2e). Can you suggest a way to assert …
=> spawn vehicles with acomms address

lrauv_ignition_plugins/test/helper/LrauvTestFixture.hh
@chapulina, @arjo129 Hi Luise and Arjo,
This is a minor change to the test fixture to output more relevant error info from the lrauv-application during testing. In the lrauv-app only FAULT and CRITICAL logging priorities are important.
Thanks!
=> update test fixture to report faults instead of errors

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/worlds/buoyant_tethys.sdf, lrauv_ignition_plugins/worlds/buoyant_tethys_at_depth.sdf, lrauv_ignition_plugins/worlds/empty_environment.sdf, lrauv_ignition_plugins/worlds/multi_lrauv.sdf, lrauv_ignition_plugins/worlds/star_world.sdf
System plugins for IMU and magnetometer sensors are scene-wide plugins.
=> Hoist ign-sensors IMU and magnetometer plugins to world SDFs

lrauv_ignition_plugins/src/WorldCommPlugin.cc, lrauv_ignition_plugins/src/WorldCommPlugin.hh
* Part of #146 
---
Originally, `WorldCommPlugin` would set the world origin to coincide with the first spawned vehicle and ignore the coordinates set from SDF. This is useful for generic simulation worlds that can be used for multiple scenarios.
But for #146 , we're creating a world that has environment features that need to be precisely geolocated. This means that we need to set the world origin before any vehicles are spawned.
This PR makes sure we support both cases:
* If `<sperical_coordinates>` isn't set from SDF, it will be set when the first vehicle is spawned.
* If it is set, then all vehicles are spawned w.r.t. that origin
Case when there's on `<spherical_coordinates>`:
1. `ign gazebo empty_environment.sdf`
2. See on inspector that there are no spherical coordinates yet
3. …
=> Use world origin spherical coordinates from SDF if set

lrauv_description/models/tethys/model.sdf.in, lrauv_description/models/tethys_equipped/model.sdf, lrauv_description/scripts/description_generator.py, lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/proto/lrauv_range_bearing_response.proto, lrauv_ignition_plugins/src/RangeBearingPlugin.cc, lrauv_ignition_plugins/test/helper/LrauvRangeBearingClient.hh, lrauv_ignition_plugins/test/test_acoustic_comms_orientation.cc, lrauv_ignition_plugins/test/test_range_bearing.cc, lrauv_ignition_plugins/worlds/tethys_acoustic_comms_test.sdf
This PR fixes the range bearing transponder to follow the conventions sent to us by MBARI. In particular the range bearing system should calculate range-bearing in the following manner:
This PR introduces a new link that orients the acoustic transponder in the correct direction. Additionally it switches from traditional spherical coordinates to the one in the above diagram. 
We also have added a new test and example world with updated transponders. This test tests the correctness of the range-bearing program with respect to the model. The transponder placements are shown here:
=> Fixes acoustic range bearing orientation.

lrauv_ignition_plugins/test/test_range_bearing.cc
Follow-up after #174. Alternatively, we could drop this test, as it is redundant with `test_acoustic_comms_orientation.cc`.
=> Fix test_range_bearing.cc

lrauv_system_tests/test/missions/test_yoyo_circle_mission.cc
Precisely what the title says. I've seen some CI jobs fail when the vehicle gets too close to surface (vertical control overshoot I presume).
=> Relax yo-yo circle mission test tolerances

lrauv_description/models/tethys/model.sdf.in, lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/worlds/windy_world.sdf, lrauv_ignition_plugins/worlds/windy_world_at_depth.sdf, lrauv_system_tests/test/CMakeLists.txt, lrauv_system_tests/test/environment/CMakeLists.txt, lrauv_system_tests/test/environment/test_surface_winds.cc, lrauv_system_tests/worlds/windy_tethys.sdf, lrauv_system_tests/worlds/windy_tethys_at_depth.sdf
Closes #149. This patch requires https://github.com/ignitionrobotics/ign-gazebo/pull/1357.
=> Add above surface winds

lrauv_ignition_plugins/src/AcousticCommsPlugin.cc, lrauv_ignition_plugins/src/ControlPanelPlugin.cc, lrauv_ignition_plugins/src/HydrodynamicsPlugin.cc, lrauv_ignition_plugins/src/RangeBearingPlugin.cc, lrauv_ignition_plugins/src/ReferenceAxis.cc, lrauv_ignition_plugins/src/ScienceSensorsSystem.cc, lrauv_ignition_plugins/src/SpawnPanelPlugin.cc, lrauv_ignition_plugins/src/TethysCommPlugin.cc, lrauv_ignition_plugins/src/TimeAnalysisPlugin.cc, lrauv_ignition_plugins/src/WorldCommPlugin.cc, lrauv_ignition_plugins/src/WorldConfigPlugin.cc, lrauv_ignition_plugins/src/comms/models/SimpleAcousticModel.cc, lrauv_system_tests/test/dynamics/test_hydrodynamics.cc, lrauv_system_tests/test/missions/test_depth_vbs_mission.cc, lrauv_system_tests/test/missions/test_pitch_mass_mission.cc, lrauv_system_tests/test/missions/test_yoyo_circle_mission.cc, lrauv_system_tests/test/simulation/test_spawn.cc, lrauv_system_tests/test/simulation/test_state.cc, lrauv_system_tests/test/vehicle/test_ahrs.cc, lrauv_system_tests/test/vehicle/test_propeller_action.cc, lrauv_system_tests/test/vehicle/test_sensor.cc, lrauv_system_tests/test/vehicle/test_sensor_timeinterpolation.cc
This PR ports IGN_PI, IGN_ADD_PLUGINS and other macros to GZ, otherwise the builds fail on the new gazebo nightlies.
=> Port IGN macros to GZ

lrauv_description/models/tethys_equipped/model.sdf, lrauv_system_tests/test/vehicle/test_ahrs.cc
Precisely what the title says. Follow-up for #158.
=> Fix AHRS config for Tethys

lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/worlds/empty_environment_with_tiles.sdf.em
This PR ports the Portuguese ledge tiles to a copy of the ``empty_environment.sdf``, called ``empty_environment_with_tiles.sdf.em``
=> Ported tiles to empty world

lrauv_ignition_plugins/CMakeLists.txt, lrauv_ignition_plugins/proto/CMakeLists.txt, lrauv_ignition_plugins/src/HydrodynamicsPlugin.cc, lrauv_ignition_plugins/src/comms/CMakeLists.txt, lrauv_ignition_plugins/src/comms/models/CMakeLists.txt, lrauv_system_tests/CMakeLists.txt
This makes the ``find_package()`` and linking macros use the ``gz`` prefixed package names.
=> Port package names in CMake to gz

lrauv_ignition_plugins/src/WorldCommPlugin.cc
Adds vehicle specific mods to the DVL topic name during spawn.
=> Add DVL mods to WorldCommPlugin

lrauv_ignition_plugins/src/RangeBearingPlugin.hh
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>
Documentation seems to have a typo that can give some trouble to an end user of the Range Bearing Plugin. According to [this](https://github.com/osrf/lrauv/blob/fc7b0647f90549d8ce5b2d1f2eb4b78dec2abc98/lrauv_ignition_plugins/src/RangeBearingPlugin.cc#L284), it seems that it publishes reponses on `/{namespace}/range_bearing/responses` instead of `/{namespace}/range_bearing/response`.
=> Typo on range bearing response topic documentation

lrauv_description/models/tethys_equipped/model.sdf, lrauv_ignition_plugins/CMakeLists.txt, lrauv_system_tests/test/vehicle/test_dvl.cc
Precisely what the title says. Follow-up after #213.
=> Relocate DVL to payload section

.github/workflows/ci.yaml, lrauv_ignition_plugins/src/TimeAnalysisPlugin.cc, lrauv_ignition_plugins/src/WorldConfigPlugin.cc, lrauv_system_tests/test/vehicle/test_sensor.cc, lrauv_system_tests/test/vehicle/test_sensor_timeinterpolation.cc
Follow-up after #239. It looks like I misinterpreted https://github.com/marketplace/actions/changed-files docs. This patch should ensure we build Gazebo Garden from source only when strictly necessary or explicitly required.
=> Build Gazebo Garden from source only when needed

lrauv_system_tests/CMakeLists.txt, lrauv_system_tests/cmake/Config.cmake.in, lrauv_system_tests/include/TestConstants.hh.in, lrauv_system_tests/include/lrauv_system_tests/TestFixture.hh, lrauv_system_tests/src/ModelObserver.cc, lrauv_system_tests/test/dynamics/test_hydrodynamics.cc, lrauv_system_tests/test/dynamics/test_hydrostatics.cc, lrauv_system_tests/test/environment/test_currents.cc, lrauv_system_tests/test/environment/test_surface_winds.cc, lrauv_system_tests/test/simulation/test_spawn.cc, lrauv_system_tests/test/simulation/test_state.cc, lrauv_system_tests/test/vehicle/test_acoustic_comms.cc, lrauv_system_tests/test/vehicle/test_acoustic_comms_multi_vehicle.cc, lrauv_system_tests/test/vehicle/test_ahrs.cc, lrauv_system_tests/test/vehicle/test_battery_full_charge.cc, lrauv_system_tests/test/vehicle/test_battery_half_charge.cc, lrauv_system_tests/test/vehicle/test_battery_low_charge.cc, lrauv_system_tests/test/vehicle/test_buoyancy_action.cc, lrauv_system_tests/test/vehicle/test_drop_weight.cc, lrauv_system_tests/test/vehicle/test_dvl.cc, lrauv_system_tests/test/vehicle/test_elevator_action.cc, lrauv_system_tests/test/vehicle/test_mass_shifter.cc, lrauv_system_tests/test/vehicle/test_propeller_action.cc, lrauv_system_tests/test/vehicle/test_range_bearing.cc, lrauv_system_tests/test/vehicle/test_rudder_action.cc
Precisely what the title says. This patch enables downstream usage of support code.
=> Install lrauv_system_tests package.

lrauv_gazebo_plugins/CMakeLists.txt
While installing gazebo on a new computer, I ran into trouble with python gazebo bindings.
I believe part of the issue is I have gazebo newly compiled from source. It's not great that
the repo does not compile at all if gz-python is not found, especially since gz-python is not
used by any core dependency. This PR adds a simple check and only runs the world generation
if the python-gazebo package is found. If the package is not found, users can still install the
simulator, however a warning is given warning users that the examples may not work.
I'm only checking for gz, but it might be worth checking for other python packages which may
or maynot come installed with an end user's work space.
=> Adds a friendly warning if the python bindings for gazebo are not found

tools/setup/Dockerfile, tools/setup/entrypoint.sh
Follow-up after #256. This patch allows the tooling to handle UID mismatches outside and inside containers gracefully.
=> Use fixuid to handle UID mismatch

lrauv_description/models/tethys/model.sdf.in
I have no idea why there are namespaces in joints. To the best of my knowledge this is not part of the SDFormat spec and it seems that gazebo is complaining about it.
=> Removes `<namespace>` in joints.

tools/setup/Dockerfile, tools/setup/enter-container.sh
Turns out SEGAFAULTs within `gz-common5` in containers were due to bad permissions and misleading error handling (or lack thereof). This patch allows `fixuid` to run recursively on $HOME by `root`ing any pre-built workspace as if it were a system dependency.
=> Fix fixuid-induced $HOME permission issues

lrauv_system_tests/test/vehicle/test_ahrs.cc, lrauv_system_tests/worlds/static_buoyant_tethys.sdf
It appears that I incorrectly assumed that making a model static upon plugin (world?) configuration was possible and I got lucky. It doesn't look like it works in general, and it has now broken the test.
This patch fixes it.
=> Make tethys always static for AHRS test
